### ISSUE TITLE
Customize nginx.conf/password protecting a subdirectory

### ISSUE THREAD

**Issue by pheraph** [TrafeX/docker-php-nginx#25]
I (noob) am trying to password protect a subdirectory. What would be an appropriate way to do this? I would like to extend the existing server config with a corresponding entry and tried with a custom .conf-file, but without success:

```
server {
    location /private {
        auth_basic "Private";
        auth_basic_user_file /private/.htpasswd; 
    }
}
```

And I tried to copy the existing `/etc/nginx/nginx.conf` from the image to my local `./nginx/` directory, but it doesn't override the existing configuration:

```yml
  frontend:
    image: trafex/alpine-nginx-php7:latest
    volumes:
      - ./app/frontend:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:8080"
```

Any help appreciated. 😄

**Comment by TrafeX** [comment]
Hi @pheraph,

If you copy the  [nginx.conf](https://github.com/TrafeX/docker-php-nginx/blob/master/config/nginx.conf) from this repo and add the custom location block in that file, you can then use that file in your docker-compose.yml file;
```
version: '3.5'
services:
  frontend:
    image: trafex/alpine-nginx-php7:latest
    volumes:
      - ./app/frontend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
```
That should do it!
